language: c

sudo: false

addons:
  apt:
    packages:
      - qemu-user
      - gcc-multilib

matrix:
  include:
  # Linux
    # x86_64
    - env: CONFIGURATION=Debug
      compiler: gcc
    - env: CONFIGURATION=Release
      compiler: gcc
    - env: CONFIGURATION=RelWithDebInfo
      compiler: gcc
    # i386
    - env: CONFIGURATION=Debug           ARCH=x86 TARGET=i386 TOOLCHAIN=gcc-i686
      compiler: gcc
    - env: CONFIGURATION=Release         ARCH=x86 TARGET=i386 TOOLCHAIN=gcc-i686
      compiler: gcc
    - env: CONFIGURATION=RelWithDebInfo  ARCH=x86 TARGET=i386 TOOLCHAIN=gcc-i686
      compiler: gcc

  # OS X
    # x86_64
    - env: CONFIGURATION=Debug
      os: osx
      compiler: clang
    - env: CONFIGURATION=Release
      os: osx
      compiler: clang
    - env: CONFIGURATION=RelWithDebInfo
      os: osx
      compiler: clang
    - env: CONFIGURATION=Debug           ARCH=x86 TARGET=i386 TOOLCHAIN=gcc-darwin-i686
      os: osx
      compiler: clang
    - env: CONFIGURATION=Release         ARCH=x86 TARGET=i386 TOOLCHAIN=gcc-darwin-i686
      os: osx
      compiler: clang
    - env: CONFIGURATION=RelWithDebInfo  ARCH=x86 TARGET=i386 TOOLCHAIN=gcc-darwin-i686
      os: osx
      compiler: clang

before_install:
  - if [ -z "${TARGET}" ]; then export TARGET=${ARCH}; fi
  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "clang" ]; then
        brew update
        brew unlink cmake
        brew install llvm cmake
      fi

script:
  - mkdir -p build && cd $_
  - |
      if [ -n "${TOOLCHAIN}" ]; then
        TC_FILE="../.cmake/Toolchains/Toolchain-${TOOLCHAIN}.cmake"
        export CMAKE_OPTS="${CMAKE_OPTS} -DARCH=${ARCH}"
        export CMAKE_OPTS="${CMAKE_OPTS} -DTARGET=${TARGET}"
        export CMAKE_OPTS="${CMAKE_OPTS} -DSYSTEM=Linux"
        export CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_TOOLCHAIN_FILE=${TC_FILE}"
      fi
  - >
      cmake
      -Wno-dev
      -DCMAKE_BUILD_TYPE=${CONFIGURATION}
      -DCMAKE_INSTALL_PREFIX=mimick-${TRAVIS_TAG}
      ${CMAKE_OPTS}
      ..
  - TERM=dumb cmake --build . -- -j4
  - |
      if [ "${TESTS:-ON}" = "ON" ]; then
        ctest
      fi
