version: 2.2.0_b{build}-{branch}

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - set "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
  - set MSYSTEM=MINGW64
  - pacman --noconfirm --needed -S base-devel git zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-i686-toolchain
  - set "PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\build;%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%"

environment:
  COVERALLS_REPO_TOKEN:
    secure: 5nuCg+faxFPeppoNNcSwVobswAVFUf8ut83vw8CX/4W2y0kZkGmwEfCUxSQWiQDU
  CI_NAME: appveyor
  CI_JOB_ID: $(APPVEYOR_JOB_ID)
  GCOV_PREFIX: $(APPVEYOR_BUILD_FOLDER)
  GENERATOR_PLATFORM: $(PLATFORM)
  matrix:
  - COMPILER: mingw
    GENERATOR: "MSYS Makefiles"
    CMAKE_OPTS: -DCMAKE_SYSTEM_PROCESSOR="%PLATFORM%" -DCMAKE_TOOLCHAIN_FILE="../.cmake/Toolchains/Toolchain-mingw-w64.cmake"
  - COMPILER: msvc
    GENERATOR: "Visual Studio 14 2015"
    CMAKE_OPTS: -DCMAKE_SYSTEM_PROCESSOR="%PLATFORM%" -A "%GENERATOR_PLATFORM%"
    CFLAGS: /MP
    CXXFLAGS: /MP

clone_depth: 5

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release
  - RelWithDebInfo

install:
  - ps: $env:RELEASE_NAME = $env:APPVEYOR_REPO_BRANCH -replace "/", "-"
  - if "%GENERATOR_PLATFORM%" == "x86" SET GENERATOR_PLATFORM=""
  # Hack to make git think it is on the tip of the repo branch
  - 'git checkout -B %APPVEYOR_REPO_BRANCH%'
  # Configure project
  - 'mkdir build && cd build'
  - >
      sh -c '
      cmake
      -Wno-dev
      -DCMAKE_INSTALL_PREFIX="mimick-%RELEASE_NAME%"
      -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
      %CMAKE_OPTS%
      -G "%GENERATOR%"
      ..
      '

build_script:
  - cmake --build .

before_deploy:
  - ps: |
        $archive = "mimick-$env:RELEASE_NAME-windows-$env:COMPILER-$env:PLATFORM"
        cmake --build . --target install
        7z a -ttar "$archive.tar" "mimick-$env:RELEASE_NAME"
        7z a -tbzip2 "../$archive.tar.bz2" "$archive.tar"
        Push-AppveyorArtifact "../$archive.tar.bz2"

test_script:
  - ps: |
        ctest
        if (-not $lastexitcode -eq 0) {
            type Testing/Temporary/LastTest.log
            $host.setshouldexit(1)
        }

notifications:

  - provider: Email
    to: [franklinmathieu@gmail.com]
    on_build_status_changed: true

deploy:
  provider: GitHub
  auth_token:
    secure: MnZZQeoxBVnpV9GSSvVok5Je0/N2d/fzG4+ITw95/tYSgZ8rleBV23a5sCwAea3r
  artifact: 'mimick-$(RELEASE_NAME)-windows-$(COMPILER)-$(PLATFORM).tar.bz2'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    configuration: RelWithDebInfo
